source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target :'TestProject' do

    pod 'Alamofire', '~> 4.8'
    pod 'SDWebImage', '3.8.1'
    pod 'MBProgressHUD', '~> 1.1.0' 
end






